### ISSUE TITLE
Oxford error "Give me all houses with 2 rooms." Variable used when already in-scope

### ISSUE THREAD

**Issue by KonradHoeffner** [AskNowQA/AutoSPARQL#19]
```
Error executing SPARQL query.
com.hp.hpl.jena.query.QueryParseException: Variable used when already in-scope: ?v1 in ((AGG ?.0 count(?y0)) AS ?v1)
    at com.hp.hpl.jena.sparql.lang.SyntaxVarScope.checkAssignment(SyntaxVarScope.java:189)
    at com.hp.hpl.jena.sparql.lang.SyntaxVarScope.checkExprListAssignment(SyntaxVarScope.java:141)
    at com.hp.hpl.jena.sparql.lang.SyntaxVarScope.checkQueryScope(SyntaxVarScope.java:92)
    at com.hp.hpl.jena.sparql.lang.SyntaxVarScope.check(SyntaxVarScope.java:66)
    at com.hp.hpl.jena.sparql.lang.SPARQLParser.validateParsedQuery(SPARQLParser.java:56)
    at com.hp.hpl.jena.sparql.lang.ParserSPARQL11.parse$(ParserSPARQL11.java:54)
    at com.hp.hpl.jena.sparql.lang.SPARQLParser.parse(SPARQLParser.java:37)
    at com.hp.hpl.jena.query.QueryFactory.parse(QueryFactory.java:139)
    at com.hp.hpl.jena.query.QueryFactory.create(QueryFactory.java:79)
    at com.hp.hpl.jena.query.QueryFactory.create(QueryFactory.java:52)
    at com.hp.hpl.jena.query.QueryFactory.create(QueryFactory.java:40)
    at com.hp.hpl.jena.query.QueryExecutionFactory.makeQuery(QueryExecutionFactory.java:565)
    at com.hp.hpl.jena.query.QueryExecutionFactory.create(QueryExecutionFactory.java:192)
    at org.aksw.autosparql.tbsl.gui.vaadin.TBSLManager.executeSelect(TBSLManager.java:959)
    at org.aksw.autosparql.tbsl.gui.vaadin.TBSLManager.fetchResult(TBSLManager.java:415)
    at org.aksw.autosparql.tbsl.gui.vaadin.TBSLManager.createAnswer(TBSLManager.java:384)
    at org.aksw.autosparql.tbsl.gui.vaadin.TBSLManager.answerQuestion(TBSLManager.java:345)
    at org.aksw.autosparql.tbsl.gui.vaadin.view.MainView$11.run(MainView.java:504)
    at java.lang.Thread.run(Thread.java:744)
Exception in thread "Thread-33" java.lang.NullPointerException
    at org.aksw.autosparql.tbsl.gui.vaadin.TBSLManager.fetchResult(TBSLManager.java:419)
    at org.aksw.autosparql.tbsl.gui.vaadin.TBSLManager.createAnswer(TBSLManager.java:384)
    at org.aksw.autosparql.tbsl.gui.vaadin.TBSLManager.answerQuestion(TBSLManager.java:345)
    at org.aksw.autosparql.tbsl.gui.vaadin.view.MainView$11.run(MainView.java:504)
    at java.lang.Thread.run(Thread.java:744)
```

**Comment by walidrelupo** [comment]
Hello ;
the code please?

**Comment by LorenzBuehmann** [comment]
@walidrelupo the code for what?

**Comment by walidrelupo** [comment]
@LorenzBuehmann  , the query!

**Comment by KonradHoeffner** [comment]
@walidrelupo thanks for participating! However this issue got opened a long time ago and the code is not actively maintained anymore. If I understand you correctly, you want to see the SPARQL query that caused the error. Unfortunately I cannot replicate this at this time.

**Comment by walidrelupo** [comment]
@KonradHoeffner , it's my pleasure to help , good luck.
