### ISSUE TITLE
Could not initialize class org.aksw.autosparql.tbsl.gui.vaadin.model.ExtendedTBSL

### ISSUE THREAD

**Issue by ziodave** [AskNowQA/AutoSPARQL#24]
When I try to access http://localhost:8080/autosparql-lite/, I get a server error:

```
javax.servlet.ServletException: java.lang.NoClassDefFoundError: Could not initialize class org.aksw.autosparql.tbsl.gui.vaadin.model.ExtendedTBSL
    at com.vaadin.terminal.gwt.server.AbstractApplicationServlet.handleServiceException(AbstractApplicationServlet.java:1010)
    at com.vaadin.terminal.gwt.server.AbstractApplicationServlet.service(AbstractApplicationServlet.java:548)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:769)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
    at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1125)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1059)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
    at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:215)
    at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
    at org.eclipse.jetty.server.Server.handle(Server.java:497)
    at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
    at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:248)
    at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:610)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:539)
    at java.lang.Thread.run(Thread.java:744)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.aksw.autosparql.tbsl.gui.vaadin.model.ExtendedTBSL
    at org.aksw.autosparql.tbsl.gui.vaadin.TBSLManager.<init>(TBSLManager.java:80)
    at org.aksw.autosparql.tbsl.gui.vaadin.UserSession.<init>(UserSession.java:26)
    at org.aksw.autosparql.tbsl.gui.vaadin.TBSLApplication.init(TBSLApplication.java:54)
    at com.vaadin.Application.start(Application.java:551)
    at com.vaadin.terminal.gwt.server.AbstractApplicationServlet.startApplication(AbstractApplicationServlet.java:1219)
    at com.vaadin.terminal.gwt.server.AbstractApplicationServlet.service(AbstractApplicationServlet.java:484)
    ... 21 more
```

I compiled with `./compile`, I will run now with `./createcompilelog` in order to attach the logs.

**Comment by arunprasathe** [comment]
hi i am getting the same issue any chance its fixed.

**Comment by KonradHoeffner** [comment]
Please post your error log arunprasathe, there seems to be a Maven issue at the moment which I am investigating right now.

**Comment by Protino** [comment]
Any updates on this issue?

**Comment by KonradHoeffner** [comment]
Due to lacking resources we unfortunately cannot maintain TBSL anymore. I recently made sure that it at least compiles, though.

**Comment by Protino** [comment]
There is no `CacheEx` class in the `jena_sparql_api/cache/extra` package anymore. But something is trying to access this class. I digged a lot but couldn't find anything. 
May be you could try this link that explains `NoClassDefFoundError` [Link](http://javarevisited.blogspot.in/2011/06/noclassdeffounderror-exception-in.html).

Anyways thanks for taking your time.

**Comment by RicardoUsbeck** [comment]
Maybe @Aklakan can help?

**Comment by CarlHoo** [comment]
You can download jena-sparql-api-core-2.10.0-22.jar and add into your project, it's the latest version include class CacheEx.

**Comment by Cassendra4** [comment]
I also get this error. can you please help me.
Problem accessing /autosparql-lite/. Reason:

    Server Error
Caused by:

javax.servlet.ServletException: javax.servlet.ServletException: java.lang.NoClassDefFoundError: Could not initialize class org.aksw.autosparql.tbsl.gui.vaadin.model.ExtendedTBSL
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:138)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:549)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:318)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:265)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:97)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
	at org.eclipse.jetty.util.thread.Invocable.invokePreferred(Invocable.java:122)
	at org.eclipse.jetty.util.thread.strategy.ExecutingExecutionStrategy.invoke(ExecutingExecutionStrategy.java:58)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:201)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:133)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)
	at java.lang.Thread.run(Thread.java:745)
Caused by: javax.servlet.ServletException: java.lang.NoClassDefFoundError: Could not initialize class org.aksw.autosparql.tbsl.gui.vaadin.model.ExtendedTBSL
	at com.vaadin.terminal.gwt.server.AbstractApplicationServlet.handleServiceException(AbstractApplicationServlet.java:1010)
	at com.vaadin.terminal.gwt.server.AbstractApplicationServlet.service(AbstractApplicationServlet.java:548)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:830)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:551)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1586)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1221)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:486)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1549)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1134)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:118)
	... 14 more
Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.aksw.autosparql.tbsl.gui.vaadin.model.ExtendedTBSL
	at org.aksw.autosparql.tbsl.gui.vaadin.TBSLManager.<init>(TBSLManager.java:80)
	at org.aksw.autosparql.tbsl.gui.vaadin.UserSession.<init>(UserSession.java:26)
	at org.aksw.autosparql.tbsl.gui.vaadin.TBSLApplication.init(TBSLApplication.java:54)
	at com.vaadin.Application.start(Application.java:551)
	at com.vaadin.terminal.gwt.server.AbstractApplicationServlet.startApplication(AbstractApplicationServlet.java:1219)
	at com.vaadin.terminal.gwt.server.AbstractApplicationServlet.service(AbstractApplicationServlet.java:484)
	... 27 more
Caused by:

javax.servlet.ServletException: java.lang.NoClassDefFoundError: Could not initialize class org.aksw.autosparql.tbsl.gui.vaadin.model.ExtendedTBSL
	at com.vaadin.terminal.gwt.server.AbstractApplicationServlet.handleServiceException(AbstractApplicationServlet.java:1010)
	at com.vaadin.terminal.gwt.server.AbstractApplicationServlet.service(AbstractApplicationServlet.java:548)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:830)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:551)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1586)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1221)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:486)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1549)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1134)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:118)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:549)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:318)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:265)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:97)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
	at org.eclipse.jetty.util.thread.Invocable.invokePreferred(Invocable.java:122)
	at org.eclipse.jetty.util.thread.strategy.ExecutingExecutionStrategy.invoke(ExecutingExecutionStrategy.java:58)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:201)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:133)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.aksw.autosparql.tbsl.gui.vaadin.model.ExtendedTBSL
	at org.aksw.autosparql.tbsl.gui.vaadin.TBSLManager.<init>(TBSLManager.java:80)
	at org.aksw.autosparql.tbsl.gui.vaadin.UserSession.<init>(UserSession.java:26)
	at org.aksw.autosparql.tbsl.gui.vaadin.TBSLApplication.init(TBSLApplication.java:54)
	at com.vaadin.Application.start(Application.java:551)
	at com.vaadin.terminal.gwt.server.AbstractApplicationServlet.startApplication(AbstractApplicationServlet.java:1219)
	at com.vaadin.terminal.gwt.server.AbstractApplicationServlet.service(AbstractApplicationServlet.java:484)
	... 27 more
Caused by:

java.lang.NoClassDefFoundError: Could not initialize class org.aksw.autosparql.tbsl.gui.vaadin.model.ExtendedTBSL
	at org.aksw.autosparql.tbsl.gui.vaadin.TBSLManager.<init>(TBSLManager.java:80)
	at org.aksw.autosparql.tbsl.gui.vaadin.UserSession.<init>(UserSession.java:26)
	at org.aksw.autosparql.tbsl.gui.vaadin.TBSLApplication.init(TBSLApplication.java:54)
	at com.vaadin.Application.start(Application.java:551)
	at com.vaadin.terminal.gwt.server.AbstractApplicationServlet.startApplication(AbstractApplicationServlet.java:1219)
	at com.vaadin.terminal.gwt.server.AbstractApplicationServlet.service(AbstractApplicationServlet.java:484)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:830)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:551)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1586)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1221)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:486)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1549)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1134)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:118)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:549)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:318)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:265)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:97)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
	at org.eclipse.jetty.util.thread.Invocable.invokePreferred(Invocable.java:122)
	at org.eclipse.jetty.util.thread.strategy.ExecutingExecutionStrategy.invoke(ExecutingExecutionStrategy.java:58)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:201)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:133)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)
	at java.lang.Thread.run(Thread.java:745)

**Comment by nmvijay** [comment]
The jena-sparql-api-core-2.10.0-22.jar contains the org/aksw/jena_sparql_api/cache/extra/CacheEx, but if you update your pom with 2.10.0-22, then you get Caused by: java.lang.ClassNotFoundException: org.aksw.jena_sparql_api.cache.extra.CacheFrontend, which is there in 2.13.0-5

So this is chicken and egg problem

**Comment by KonradHoeffner** [comment]
I got a different error, namely that the artifacts jena-arq and com.googlecode.concurrentlinkedhashmap were not found, which I fixed by increasing jena-arq version to 2.13.0 and com.googlecode.concurrentlinkedhashmap to 1.4.2. Can you try again after git pull?

**Comment by CarlHoo** [comment]
The issue still open?!
@nmvijay I just import the jena-sparql-api-core-2.10.0-22.jar into my project directly, not update the pom, then set the order lower than maven lib, get both chicken and egg!

**Comment by chuanwise** [comment]
> The issue still open?! @nmvijay I just import the jena-sparql-api-core-2.10.0-22.jar into my project directly, not update the pom, then set the order lower than maven lib, get both chicken and egg!

I met the same problem, what's 'import the jena-sparql-api-core-2.10.0-22.jar into my project directly'? I tried to import it to a idea project and it still error

**Comment by KonradHoeffner** [comment]
This repository should probably be archived as it hasn't been maintained for a long time but I don't currently have the rights to do that.
@Chuanwise: Can you tell us about your use case for using AutoSPARQL? If it is critical for you maybe someone can find some time to investigate.
@JensLehmann @GezimSejdiu @mohnish-rygbee I recommend archiving, can you chime in whether you agree and if necessary make the change?

**Comment by chuanwise** [comment]
> This repository should probably be archived as it hasn't been maintained for a long time but I don't currently have the rights to do that. @Chuanwise: Can you tell us about your use case for using AutoSPARQL? If it is critical for you maybe someone can find some time to investigate. @JensLehmann @GezimSejdiu @mohnish-rygbee I recommend archiving, can you chime in whether you agree and if necessary make the change?

I cloned the repo and tried to run `mvn jetty:run` but it doesn't work. With the help of this issue, I downloaded jena-sparql-api-core-2.10.0-22.jar and tried to import it by adding system-scoped dependency to `pom.xml` or adding it to library setting in jetbrains idea project structure, but it still error. 

I didn't input anything because AutoSPARQL hadn't launched successfully.

**Comment by KonradHoeffner** [comment]
I mean, can you please explain why you need to use a more than 10 year old tool in 2023 that hasn't been maintained in many years especially in such an area of rapid progress.
If you tell us about your use case, we may be able to suggest an alternative tool that is more up to date, or if it is indeed a use case where another existing tool does not suffice we may allocate resources to fix the problem.
